parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): 'sqlite:///%kernel.project_dir%/var/db/data.db3'

doctrine:
    dbal:
        driver: 'pdo_sqlite'
        # configure these for your database server
        # driver: 'pdo_mysql'
        # server_version: '5.7'
        # charset: utf8mb4
        # default_table_options:
           # charset: utf8mb4
           # collate: utf8mb4_unicode_ci
        # path: '%env(resolve:DATABASE_URL)%'
        # path: 'D:\Documents\Workflow\xampp\dev\simple-converter\var\db\data.db3'
        url: 'sqlite:///%kernel.project_dir%/var/db/data.db3'
        charset: UTF8

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
